// Mythic Artifacts — 20 unique legendary items. Each is one-of-a-kind
// in existence. Once awarded, cannot be lost, sold, or destroyed; they
// live permanently on the hero. AI references them organically in
// scenes (1-in-4 frequency cap) and offers them as decisive choice
// options when contextually appropriate.

export interface MythicArtifact {
  id: string;
  name: string;
  icon: string;
  rarity: "mythic";
  description: string;
  storyUse: string;
  acquisition: string;
  flavorText: string;
  powerLevel: "high" | "medium" | "medium-low";
}

export const MYTHIC_ARTIFACTS: MythicArtifact[] = [
  { id: "medusas_head",        name: "Medusa's Severed Head",        icon: "🐍", rarity: "mythic", description: "The serpent-crowned head of the gorgon Medusa, preserved by Athena's magic. Her gaze still petrifies.",                       storyUse: "Unfurl the head — mortals below Heroic tier turn to stone instantly. Demigod tier resist; gods are immune.",                                                         acquisition: "Defeat Medusa in her labyrinth",                                                  flavorText: "Mortals look away when you draw it. Even allies.",                          powerLevel: "high" },
  { id: "aegis_shield",        name: "The Aegis",                    icon: "🛡️", rarity: "mythic", description: "A shield bearing the face of Medusa, gifted by Athena to her chosen. Repels all magic and strikes fear into enemies.",         storyUse: "When raised in combat, enemies must succeed a Courage check or flee. Reflects magical attacks.",                                                                     acquisition: "Earned by completing Athena's adventure with honor",                              flavorText: "To bear the Aegis is to carry Athena's favor itself.",                       powerLevel: "high" },
  { id: "thunderbolt_fragment",name: "Shard of Zeus's Thunderbolt",  icon: "⚡", rarity: "mythic", description: "A jagged fragment of pure storm-iron, still humming with divine electricity. Burns to touch.",                                  storyUse: "Throw at any single target for devastating lightning damage. Once per adventure; regenerates between adventures.",                                                   acquisition: "Reward from Zeus after completing his trial",                                     flavorText: "The sky itself answers when you hold it aloft.",                             powerLevel: "high" },
  { id: "lyre_of_orpheus",     name: "Lyre of Orpheus",              icon: "🎵", rarity: "mythic", description: "The legendary lyre that charmed Hades himself. Strings of golden hair, frame of black olivewood.",                              storyUse: "Play to soothe any hostile being (Charisma +20). Even monsters pause to listen. Can soothe the dead.",                                                              acquisition: "Found in Orpheus's tomb, after solving a music-based puzzle",                     flavorText: "The strings remember every song that has ever moved a heart.",               powerLevel: "medium" },
  { id: "helm_of_hades",       name: "Helm of Darkness",             icon: "👑", rarity: "mythic", description: "The helm of Hades, forged by Cyclopes. Renders the wearer completely invisible — even to gods.",                                storyUse: "While worn, you cannot be seen or heard. Lasts one scene per adventure. Doesn't work in direct sunlight.",                                                           acquisition: "Borrowed (then earned) from Hades after a great service",                         flavorText: "Even your own shadow forgets you.",                                          powerLevel: "high" },
  { id: "cornucopia",          name: "Cornucopia of Plenty",         icon: "🌾", rarity: "mythic", description: "A horn that pours forth food, wine, and healing herbs without end. Bound in gold and ivy.",                                    storyUse: "Heal allies fully (once per adventure). Feed an army for a day. Sober a drunkard. Cure mild ailments.",                                                              acquisition: "Reward from Demeter for restoring a blighted harvest",                            flavorText: "Tilt it and the world spills forth what it most needs.",                     powerLevel: "medium" },
  { id: "golden_fleece",       name: "The Golden Fleece",            icon: "✨", rarity: "mythic", description: "The legendary fleece of a divine ram, glowing softly. Wearing it brings royal authority and divine protection.",                  storyUse: "While worn: +10 Charisma in royal courts; immune to one fatal blow per adventure; kings recognize your authority.",                                                  acquisition: "Reclaimed from the temple where Jason left it",                                   flavorText: "It hums softly, as if remembering Jason's voyage.",                          powerLevel: "high" },
  { id: "caduceus",            name: "Caduceus of Hermes",           icon: "🐍", rarity: "mythic", description: "Hermes's winged staff entwined with two serpents. Symbol of negotiation, healing, and divine swiftness.",                       storyUse: "Grants safe passage anywhere in Greece (NPCs recognize divine authority). Heal one ally per scene. +10 persuasion.",                                                acquisition: "Gift from Hermes after a successful trickster adventure",                         flavorText: "The serpents whisper secrets only you can hear.",                            powerLevel: "medium" },
  { id: "wings_of_daedalus",   name: "Wings of Daedalus",            icon: "🪶", rarity: "mythic", description: "The original wings crafted by Daedalus — wax and feather, perfectly preserved. Functional but delicate.",                       storyUse: "Fly for the duration of one scene. Useful for escape, crossing terrain, attacking from above. Cannot fly near direct sun (wax melts).",                              acquisition: "Recovered from the cave where Daedalus hid them after Icarus's fall",             flavorText: "Light. Surprisingly fragile. Earned with every flight.",                    powerLevel: "medium" },
  { id: "bow_of_artemis",      name: "Silver Bow of the Hunt",       icon: "🏹", rarity: "mythic", description: "Artemis's personal bow, gleaming silver. Arrows fired from it never miss their intended target.",                              storyUse: "Any ranged attack with this bow auto-succeeds (no roll required). Three arrows per adventure. Restocks at moonrise.",                                                acquisition: "Earned by completing the Great Hunt with Artemis",                                flavorText: "The string sings before you even draw it.",                                  powerLevel: "high" },
  { id: "spear_of_achilles",   name: "Spear of Achilles",            icon: "🔱", rarity: "mythic", description: "The legendary spear of Achilles, forged in dragon-fire. Wounds it inflicts never fully heal.",                                  storyUse: "+5 damage as primary weapon; wounds dealt cannot be healed by potions or magic for 24 in-game hours.",                                                              acquisition: "Recovered from a hidden chamber beneath Troy's ruins",                            flavorText: "Even gods bleed slowly when struck by it.",                                  powerLevel: "high" },
  { id: "shield_of_perseus",   name: "Mirror Shield of Perseus",     icon: "🪞", rarity: "mythic", description: "The polished bronze shield Perseus used to defeat Medusa. Surface reflects everything — including magic.",                    storyUse: "Reflects all magical attacks back at attacker. Safely view gorgons, basilisks, divine apparitions.",                                                                acquisition: "Won from a trickster god who had stolen it",                                      flavorText: "You see yourself in it, but also more than yourself.",                       powerLevel: "medium" },
  { id: "sandals_hermes",      name: "Winged Sandals",               icon: "👡", rarity: "mythic", description: "Hermes's winged sandals — small bronze wings flutter at the heels.",                                                            storyUse: "Travel anywhere in Greece in moments. +10 Agility while worn. Cannot be tripped or knocked down.",                                                                   acquisition: "Borrowed from Hermes (and never returned, with his amused permission)",            flavorText: "The wings beat softly even when you stand still.",                          powerLevel: "medium" },
  { id: "apple_of_discord",    name: "Apple of Discord",             icon: "🍎", rarity: "mythic", description: "A golden apple inscribed 'For the Fairest'. Causes uncontrollable rivalry wherever it appears.",                              storyUse: "Throw into a group of NPCs — they will fight over it, distracting them entirely.",                                                                                  acquisition: "Found in a long-abandoned wedding hall",                                          flavorText: "It feels warm in your hand, but burns when you look away.",                  powerLevel: "medium" },
  { id: "lyre_of_apollo",      name: "Apollo's Golden Lyre",         icon: "🎼", rarity: "mythic", description: "The original lyre played by Apollo. Music from it can heal, inspire, or break enchantments.",                                  storyUse: "Play to heal all allies; break a curse; or charm any single NPC into helping you. Once per adventure.",                                                              acquisition: "Won in a music contest against a satyr",                                          flavorText: "It plays itself if you forget the next note.",                              powerLevel: "medium" },
  { id: "mask_of_dionysus",    name: "Mask of Dionysus",             icon: "🎭", rarity: "mythic", description: "A mask of vine-leaves and gold. Wearing it grants any disguise the wearer wishes.",                                          storyUse: "While worn, appear as anyone the user describes — NPC, noble, even a god's avatar. Lasts one scene.",                                                                acquisition: "Stolen (with permission, after a wild festival) from Dionysus himself",            flavorText: "The mask laughs softly when you put it on.",                                 powerLevel: "medium" },
  { id: "trident_fragment",    name: "Fragment of Poseidon's Trident", icon: "🔱", rarity: "mythic", description: "A shard from one tine of Poseidon's great trident. Commands sea and storm.",                                                  storyUse: "Calm or summon storms; speak with sea creatures; breathe underwater while held.",                                                                                    acquisition: "Reward from Poseidon after defeating a sea monster",                              flavorText: "Held to the wind, you hear the ocean speak.",                                powerLevel: "high" },
  { id: "olive_branch_athena", name: "Branch of the First Olive Tree", icon: "🌿", rarity: "mythic", description: "A branch from the original olive tree Athena gifted to Athens. Living, never withering.",                                    storyUse: "Plant it anywhere — it grows into a tree within minutes, providing shelter, fruit, sanctuary. Athena watches over its bearer.",                                       acquisition: "Earned through a non-violent victory in Athens",                                  flavorText: "It hums when peace is near.",                                                powerLevel: "medium" },
  { id: "eye_of_graeae",       name: "Eye of the Graeae",            icon: "👁️", rarity: "mythic", description: "The single eye the three Graeae sisters shared. Shows hidden things, future glimpses, ancient secrets.",                       storyUse: "Once per adventure, see something normally hidden — secret door, traitor's thoughts, near-future moment.",                                                          acquisition: "Tricked from the Graeae by clever bargain",                                       flavorText: "You see what they saw. Sometimes you wish you hadn't.",                     powerLevel: "medium" },
  { id: "phoenix_feather",     name: "Phoenix Feather",              icon: "🔥", rarity: "mythic", description: "A single feather from a true phoenix, glowing softly. Resurrects the bearer once.",                                          storyUse: "When the bearer would die, they return to life with full HP. Single use — feather burns away.",                                                                      acquisition: "Plucked from the ash of a phoenix's rebirth (with its permission)",               flavorText: "It warms your hand when death is near.",                                     powerLevel: "medium-low" },
];

export function getArtifactById(id: string): MythicArtifact | undefined {
  return MYTHIC_ARTIFACTS.find(a => a.id === id);
}
