// Glam Studio — per-profile lookbook save/load.
//
// Mirrors the StyleStudio (sketch) save pattern: profile-scoped
// localStorage key + cloudBlob sync for cross-device. Each saved Look is
// a small JSON config + an optional PNG dataUrl preview generated by the
// builder via THREE.WebGLRenderer.domElement.toDataURL.

import {
  getActiveProfileId, profileKey,
} from "../../profiles/store";
import { setBlob as cloudSet, subscribeBlob as cloudSubscribe } from "../../sync/cloudBlob";
import type { SavedLook } from "../data/manifest";

// New keys — distinct from the SVG dressup so the two coexist during the
// transition (Phase 5 cuts the SVG over).
const SAVED_BASE = "dd_glam_saved";
const SAVED_BLOB = "glam_saved_v1";

function savedKey() { return profileKey(SAVED_BASE); }

export function loadLookbook(): SavedLook[] {
  try {
    const raw = localStorage.getItem(savedKey());
    return raw ? (JSON.parse(raw) as SavedLook[]) : [];
  } catch { return []; }
}

export function persistLookbook(list: SavedLook[]) {
  try { localStorage.setItem(savedKey(), JSON.stringify(list)); } catch { /* ignore */ }
  const pid = getActiveProfileId();
  if (pid) {
    try { cloudSet(pid, SAVED_BLOB, list); } catch { /* ignore */ }
  }
}

export function subscribeLookbook(cb: (list: SavedLook[]) => void): (() => void) | null {
  const pid = getActiveProfileId();
  if (!pid) return null;
  return cloudSubscribe<SavedLook[]>(pid, SAVED_BLOB, (remote) => {
    if (!remote || !Array.isArray(remote)) return;
    try { localStorage.setItem(savedKey(), JSON.stringify(remote)); } catch { /* ignore */ }
    cb(remote);
  });
}

export function addLook(list: SavedLook[], look: SavedLook): SavedLook[] {
  // Cap at 24 looks per profile to keep cloud blob small.
  const next = [...list, look].slice(-24);
  persistLookbook(next);
  return next;
}

export function deleteLook(list: SavedLook[], id: string): SavedLook[] {
  const next = list.filter(s => s.id !== id);
  persistLookbook(next);
  return next;
}
