// Cosmic Squad — hand-tuned mission templates.
// Difficulty ramps from 1 (cadet's first sortie) to 5 (fleet-admiral
// finale). Each mission has a briefing the user can read or have the
// AI rewrite into something more atmospheric.

import type { MissionTemplate } from "./types";

export const MISSIONS: MissionTemplate[] = [
  {
    id: "m01_first_blood",
    title: "First Blood",
    difficulty: 1,
    objective: "destroy_all",
    turnLimit: 18,
    enemyCount: [2, 3],
    enemyClasses: ["imperial_ty_fighter"],
    maxWingmen: 1,
    rewardRank: 50,
    rewardCredits: 200,
    briefing: "A patrol of light interceptors strayed into our sector. Easy mark for a rookie sortie. Hold formation with your wingman and clear the field.",
    intel: "TY Interceptors. No shields. Glass jaw. Watch for swarm bonuses.",
    hazards: "None.",
  },
  {
    id: "m02_supply_run",
    title: "Supply Run",
    difficulty: 1,
    objective: "escort",
    turnLimit: 16,
    enemyCount: [2, 3],
    enemyClasses: ["imperial_ty_fighter", "covenant_seraph"],
    maxWingmen: 1,
    rewardRank: 60,
    rewardCredits: 250,
    unlockClass: "recon_scout",
    briefing: "Escort a relief shuttle to the far side of the grid. Keep the shuttle's hull above 0% — credits and fresh hardware on the line.",
    intel: "Shuttle hp 50, no shields. It limps east at 2 cells/turn.",
    hazards: "Asteroid belt midfield.",
  },
  {
    id: "m03_ambush",
    title: "Cold Ambush",
    difficulty: 2,
    objective: "destroy_all",
    turnLimit: 22,
    enemyCount: [3, 4],
    enemyClasses: ["covenant_seraph", "imperial_ty_fighter"],
    maxWingmen: 2,
    rewardRank: 100,
    rewardCredits: 400,
    briefing: "Intel says a Covenant strike wing is staging behind a debris field. Decloak, decide, decimate.",
    intel: "Seraphs have regenerating shields — focus fire wins.",
    hazards: "Debris reduces visibility 1 cell.",
  },
  {
    id: "m04_hold_the_line",
    title: "Hold the Line",
    difficulty: 2,
    objective: "survive_turns",
    turnLimit: 14,
    enemyCount: [4, 5],
    enemyClasses: ["imperial_ty_fighter", "klingon_raider"],
    maxWingmen: 2,
    rewardRank: 110,
    rewardCredits: 500,
    unlockClass: "viper_mark_seven",
    briefing: "Reinforcements are 10 turns out. Don't die. Don't let them through.",
    intel: "Mixed enemy waves on a 3-turn cadence.",
  },
  {
    id: "m05_bomb_run",
    title: "Bomb Run",
    difficulty: 3,
    objective: "bomb_run",
    turnLimit: 20,
    enemyCount: [3, 4],
    enemyClasses: ["covenant_phantom", "imperial_ty_fighter"],
    maxWingmen: 2,
    rewardRank: 160,
    rewardCredits: 750,
    briefing: "A Phantom drop-ship hides a fuel cache deep in enemy territory. Reach the marker. Drop a Nova. Don't be there when it lights up.",
    intel: "AOE blast radius 2 cells. You and your wingmen take damage if too close.",
    hazards: "Nova AOE — keep 3+ cells clear.",
  },
  {
    id: "m06_rescue",
    title: "Eject and Recover",
    difficulty: 3,
    objective: "rescue",
    turnLimit: 18,
    enemyCount: [3, 4],
    enemyClasses: ["klingon_raider", "covenant_seraph"],
    maxWingmen: 2,
    rewardRank: 180,
    rewardCredits: 800,
    unlockClass: "normandy",
    briefing: "A friendly pilot is drifting in an escape pod. Reach them and clear hostiles in a 4-cell radius before extraction.",
    intel: "Escape pod has 25 hp, no shields. One hit and your wingman is lost permanently.",
    hazards: "Pod cannot move.",
  },
  {
    id: "m07_ace_duel",
    title: "Ace's Choice",
    difficulty: 4,
    objective: "ace_duel",
    turnLimit: 18,
    enemyCount: [1, 1],
    enemyClasses: ["klingon_raider"],
    maxWingmen: 0,
    rewardRank: 220,
    rewardCredits: 1000,
    briefing: "A Klingon ace has been hunting our pilots. He's challenged you, solo, no wingmen. Honor demands you answer.",
    intel: "Enemy ace has +25% damage and cloaks turn 1.",
    hazards: "Honor: no retreat allowed.",
  },
  {
    id: "m08_capital_kill",
    title: "Kill the Destroyer",
    difficulty: 4,
    objective: "destroy_target",
    turnLimit: 18,
    enemyCount: [4, 5],
    enemyClasses: ["imperial_destroyer", "imperial_ty_fighter", "covenant_phantom"],
    maxWingmen: 3,
    rewardRank: 280,
    rewardCredits: 1500,
    unlockClass: "rebel_a_class",
    briefing: "An Imperial Destroyer has been raiding shipping lanes. Capital with escorts. Strip the escorts, then break the dreadnought.",
    intel: "Destroyer hp 400. Strong front shields. Hit the rear arc.",
    hazards: "Six weapon slots on the destroyer — it broadsides every turn.",
  },
  {
    id: "m09_infiltrate",
    title: "Silent Approach",
    difficulty: 4,
    objective: "infiltrate",
    turnLimit: 14,
    enemyCount: [4, 5],
    enemyClasses: ["covenant_seraph", "klingon_raider"],
    maxWingmen: 1,
    rewardRank: 240,
    rewardCredits: 1100,
    briefing: "Reach the target waypoint without being detected. Stay 4+ cells from every patrol or the mission burns.",
    intel: "Each enemy has a 4-cell sensor cone facing their travel vector.",
    hazards: "Detection = instant fail.",
  },
  {
    id: "m10_fleet_admiral",
    title: "Last Stand",
    difficulty: 5,
    objective: "destroy_all",
    turnLimit: 30,
    enemyCount: [6, 8],
    enemyClasses: ["imperial_destroyer", "romulan_warbird", "covenant_phantom", "covenant_seraph", "imperial_ty_fighter"],
    maxWingmen: 4,
    rewardRank: 500,
    rewardCredits: 3000,
    unlockClass: "federation_explorer",
    briefing: "Every faction has converged on the system. Our full squadron flies. This is the one we tell stories about.",
    intel: "Two capitals + four mediums + waves of light fighters.",
    hazards: "Nebula field reduces all shield regen.",
  },
];

export function getMission(id: string): MissionTemplate | undefined {
  return MISSIONS.find(m => m.id === id);
}

export function missionsForRank(rank: number): MissionTemplate[] {
  return MISSIONS.filter(m => m.difficulty <= Math.max(1, rank + 1));
}
