// Cosmic Squad — 20-ship roster.
// Stat blocks for every flyable class. The narrative "inspiredBy" name
// is the visual reference; the in-game name is a thin reskin so we
// don't ape any specific IP too closely. Each ship is tuned around a
// role (interceptor / striker / brawler / capital / support).

import type { ShipClass } from "./types";

export const SHIP_CLASSES: ShipClass[] = [
  {
    id: "rebel_x_class",
    name: "X-Class Starfighter",
    inspiredBy: "X-Wing",
    era: "starwars",
    faction: "Republic Fleet",
    size: "small",
    hp: 60,
    speed: 5,
    maneuverability: 8,
    weaponSlots: 3,
    shieldFront: 20, shieldRear: 15, shieldLR: 15,
    description: "Iconic four-engine snub fighter. Balanced and forgiving — the rookie's first real bird.",
    special: "S-foils: +1 maneuverability when shields below 25%.",
    unlockRank: 0,
    primaryColor: "#d97757",
    accent: "#f3c969",
  },
  {
    id: "imperial_ty_fighter",
    name: "TY Interceptor",
    inspiredBy: "TIE Fighter",
    era: "starwars",
    faction: "Imperium",
    size: "small",
    hp: 35,
    speed: 7,
    maneuverability: 10,
    weaponSlots: 2,
    shieldFront: 0, shieldRear: 0, shieldLR: 0,
    description: "Twin ion engines, no shields, glass jaw. Lethal in numbers — fragile alone.",
    special: "Swarm bonus: +2 damage when within 3 cells of another TY.",
    unlockRank: 1,
    primaryColor: "#3a4a6a",
    accent: "#9aa8c0",
  },
  {
    id: "rebel_a_class",
    name: "A-Class Interceptor",
    inspiredBy: "A-Wing",
    era: "starwars",
    faction: "Republic Fleet",
    size: "small",
    hp: 45,
    speed: 8,
    maneuverability: 10,
    weaponSlots: 2,
    shieldFront: 12, shieldRear: 12, shieldLR: 8,
    description: "Fastest hull in the fleet. Hit-and-run specialist with thin armor.",
    special: "Afterburner: +3 speed once per battle.",
    unlockRank: 2,
    primaryColor: "#c3534c",
    accent: "#e8a14b",
  },
  {
    id: "imperial_destroyer",
    name: "Imperial Destroyer",
    inspiredBy: "Star Destroyer",
    era: "starwars",
    faction: "Imperium",
    size: "capital",
    hp: 400,
    speed: 1,
    maneuverability: 2,
    weaponSlots: 6,
    shieldFront: 80, shieldRear: 50, shieldLR: 60,
    description: "Wedge-shaped dreadnought. Slow, fearsome, six-slot loadout. Capital escort target.",
    special: "Broadside: extra weapon slot fires each turn from rear arc.",
    unlockRank: 5,
    primaryColor: "#7d8a9c",
    accent: "#c9d2dd",
  },
  {
    id: "spartan_lancer",
    name: "Spartan Lancer",
    inspiredBy: "Pelican / UNSC frigate",
    era: "halo",
    faction: "UNSC",
    size: "medium",
    hp: 110,
    speed: 4,
    maneuverability: 5,
    weaponSlots: 4,
    shieldFront: 30, shieldRear: 25, shieldLR: 25,
    description: "Workhorse human frigate. Tough plating, average everything else.",
    special: "MAC round: first shot each battle deals double damage.",
    unlockRank: 3,
    primaryColor: "#4a5e3a",
    accent: "#a8b988",
  },
  {
    id: "covenant_seraph",
    name: "Seraph Striker",
    inspiredBy: "Covenant Seraph",
    era: "halo",
    faction: "Covenant Remnant",
    size: "small",
    hp: 55,
    speed: 6,
    maneuverability: 8,
    weaponSlots: 3,
    shieldFront: 25, shieldRear: 20, shieldLR: 20,
    description: "Curved purple plasma fighter. Energy shields recharge between turns.",
    special: "Shields regenerate 5 per facet per turn out of combat.",
    unlockRank: 3,
    primaryColor: "#6a3a7d",
    accent: "#d098f0",
  },
  {
    id: "covenant_phantom",
    name: "Phantom Reaver",
    inspiredBy: "Covenant Phantom",
    era: "halo",
    faction: "Covenant Remnant",
    size: "medium",
    hp: 130,
    speed: 3,
    maneuverability: 4,
    weaponSlots: 4,
    shieldFront: 35, shieldRear: 30, shieldLR: 30,
    description: "Dropship-gunship hybrid. Heavy plasma, weak rear arc.",
    special: "Plasma cannon ignores 10 shield on direct hit.",
    unlockRank: 4,
    primaryColor: "#5a4a8a",
    accent: "#a890e0",
  },
  {
    id: "federation_explorer",
    name: "Federation Explorer",
    inspiredBy: "Galaxy-class starship",
    era: "startrek",
    faction: "Federation",
    size: "capital",
    hp: 320,
    speed: 2,
    maneuverability: 3,
    weaponSlots: 5,
    shieldFront: 70, shieldRear: 60, shieldLR: 60,
    description: "Saucer-and-nacelle science capital. Phasers, photons, and a diplomacy officer.",
    special: "Phaser sweep: hits all enemies within 4 cells for 15 damage.",
    unlockRank: 5,
    primaryColor: "#5a7a9c",
    accent: "#e8d8b8",
  },
  {
    id: "klingon_raider",
    name: "Klingon Raider",
    inspiredBy: "Bird of Prey",
    era: "startrek",
    faction: "Klingon Empire",
    size: "medium",
    hp: 95,
    speed: 5,
    maneuverability: 7,
    weaponSlots: 3,
    shieldFront: 25, shieldRear: 20, shieldLR: 18,
    description: "Wings-down hunter. Disruptors, decloak ambush, no honor lost.",
    special: "Cloak: invisible to homing missiles for 2 turns once per battle.",
    unlockRank: 4,
    primaryColor: "#3a5a3a",
    accent: "#88c098",
  },
  {
    id: "romulan_warbird",
    name: "Romulan Warbird",
    inspiredBy: "D'deridex Warbird",
    era: "startrek",
    faction: "Romulan Star Empire",
    size: "capital",
    hp: 280,
    speed: 2,
    maneuverability: 4,
    weaponSlots: 5,
    shieldFront: 60, shieldRear: 55, shieldLR: 50,
    description: "Green talon-shaped predator. Plasma torpedoes and a singularity drive.",
    special: "Plasma torpedo deals damage-over-time (8/turn for 3 turns).",
    unlockRank: 6,
    primaryColor: "#3a7a4a",
    accent: "#88e0a0",
  },
  {
    id: "shuttle_orbiter",
    name: "Orbiter Shuttle",
    inspiredBy: "Space Shuttle",
    era: "real",
    faction: "Earth Agency",
    size: "medium",
    hp: 75,
    speed: 3,
    maneuverability: 4,
    weaponSlots: 2,
    shieldFront: 10, shieldRear: 10, shieldLR: 8,
    description: "Real-world shuttle stand-in. Underpowered weapons, sturdy heat tiles.",
    special: "Reentry: takes 50% damage from AOE attacks.",
    unlockRank: 0,
    primaryColor: "#d8d8d8",
    accent: "#3a3a3a",
  },
  {
    id: "dragon_capsule",
    name: "Dragon Capsule",
    inspiredBy: "SpaceX Dragon",
    era: "real",
    faction: "Earth Agency",
    size: "small",
    hp: 50,
    speed: 5,
    maneuverability: 7,
    weaponSlots: 2,
    shieldFront: 8, shieldRear: 8, shieldLR: 6,
    description: "Modern reusable capsule. Nimble for its class. Splashes down with style.",
    special: "Reusable: revives once per campaign if destroyed.",
    unlockRank: 1,
    primaryColor: "#f0f0f0",
    accent: "#0a0a0a",
  },
  {
    id: "apollo_capsule",
    name: "Apollo Capsule",
    inspiredBy: "Apollo CSM",
    era: "real",
    faction: "Earth Agency",
    size: "small",
    hp: 45,
    speed: 4,
    maneuverability: 6,
    weaponSlots: 1,
    shieldFront: 6, shieldRear: 6, shieldLR: 6,
    description: "Cone-on-cylinder veteran. Slow, low loadout, plenty of heart.",
    special: "+50% rank points earned when piloting an Apollo.",
    unlockRank: 0,
    primaryColor: "#c8c8c8",
    accent: "#9a7a3a",
  },
  {
    id: "viper_mark_seven",
    name: "Viper Mk VII",
    inspiredBy: "BSG Viper",
    era: "galactica",
    faction: "Colonial Fleet",
    size: "small",
    hp: 55,
    speed: 6,
    maneuverability: 9,
    weaponSlots: 2,
    shieldFront: 0, shieldRear: 0, shieldLR: 0,
    description: "Unshielded duelist. Pure kinetic guns and pilot skill.",
    special: "Critical hit chance +15% — pure gunfighter.",
    unlockRank: 2,
    primaryColor: "#a09080",
    accent: "#e8c878",
  },
  {
    id: "normandy",
    name: "SR-Class Frigate",
    inspiredBy: "Normandy SR-2",
    era: "masseffect",
    faction: "Systems Alliance",
    size: "medium",
    hp: 120,
    speed: 5,
    maneuverability: 6,
    weaponSlots: 4,
    shieldFront: 30, shieldRear: 25, shieldLR: 25,
    description: "Stealth frigate with eezo core. Sleek, balanced, and runs cool.",
    special: "Stealth: cannot be targeted by homing missiles for first 2 turns.",
    unlockRank: 4,
    primaryColor: "#3a4a6a",
    accent: "#e8a040",
  },
  {
    id: "rapier_two",
    name: "Rapier II",
    inspiredBy: "Wing Commander Rapier",
    era: "wingcommander",
    faction: "Terran Confederation",
    size: "small",
    hp: 65,
    speed: 6,
    maneuverability: 8,
    weaponSlots: 3,
    shieldFront: 18, shieldRear: 15, shieldLR: 12,
    description: "Twin-cockpit medium fighter. Beloved by ace pilots.",
    special: "Ace bonus: +10% damage when a wingman is within 4 cells.",
    unlockRank: 2,
    primaryColor: "#5a5a8a",
    accent: "#c0c0e8",
  },
  {
    id: "interceptor_drone",
    name: "Interceptor Drone",
    inspiredBy: "EVE Online interceptor",
    era: "eve",
    faction: "Capsuleer Cartel",
    size: "small",
    hp: 40,
    speed: 9,
    maneuverability: 10,
    weaponSlots: 2,
    shieldFront: 8, shieldRear: 8, shieldLR: 8,
    description: "Unmanned hyper-fast harasser. Skirmisher with paper armor.",
    special: "Warp drive: teleport 5 cells once per battle.",
    unlockRank: 3,
    primaryColor: "#7a3a3a",
    accent: "#e8a0a0",
  },
  {
    id: "minbari_flyer",
    name: "Minbari Flyer",
    inspiredBy: "Minbari Nial",
    era: "babylon5",
    faction: "Minbari Federation",
    size: "medium",
    hp: 100,
    speed: 6,
    maneuverability: 9,
    weaponSlots: 3,
    shieldFront: 28, shieldRear: 22, shieldLR: 22,
    description: "Crystalline three-prong starfighter. Targeting computer the Earth Alliance can't crack.",
    special: "Targeting computer: +20% accuracy at any range.",
    unlockRank: 5,
    primaryColor: "#3a6a8a",
    accent: "#a0d8e8",
  },
  {
    id: "aegis_destroyer",
    name: "Aegis Destroyer",
    inspiredBy: "near-future naval doctrine",
    era: "future",
    faction: "Sol Coalition",
    size: "capital",
    hp: 360,
    speed: 2,
    maneuverability: 3,
    weaponSlots: 5,
    shieldFront: 75, shieldRear: 65, shieldLR: 60,
    description: "Anti-missile capital. Specializes in point defense and area denial.",
    special: "Point defense: 30% chance to shoot down incoming homing missiles.",
    unlockRank: 6,
    primaryColor: "#4a4a4a",
    accent: "#c0c0c0",
  },
  {
    id: "recon_scout",
    name: "Recon Scout",
    inspiredBy: "generic near-future scout",
    era: "future",
    faction: "Sol Coalition",
    size: "small",
    hp: 50,
    speed: 7,
    maneuverability: 9,
    weaponSlots: 2,
    shieldFront: 12, shieldRear: 12, shieldLR: 10,
    description: "Long-range eyes of the fleet. Sensor sweep reveals the map.",
    special: "Sensor sweep: reveals all enemy positions for one turn.",
    unlockRank: 1,
    primaryColor: "#6a7a4a",
    accent: "#d8e8a0",
  },
];

export function getShipClass(id: string): ShipClass | undefined {
  return SHIP_CLASSES.find(s => s.id === id);
}

/** Ships available at the given rank index. */
export function shipsForRank(rank: number): ShipClass[] {
  return SHIP_CLASSES.filter(s => s.unlockRank <= rank);
}
